server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 200161
    driver-class-name: com.mysql.cj.jdbc.Driver
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#Eureka配置：服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka/
#测试信息
test: update!the message sending by config-service-git
# 度量指标监控与健康检查
management:
  endpoints:
    web:
      base-path: /actuator    # 访问端点根路径，默认为 /actuator
      exposure:
        include: bus-refresh  # 需要开启的端点
        #exclude:             # 不需要开启的端点
